[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remapping = ["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/","forge-std/=lib/forge-std/src/"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

ffi = true